#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry 'Microsoft Windows 11' {
        insmod part_gpt
        insmod chain
        insmod fat
        search --fs-uuid --no-floppy --set=root 1E0C-FFAE 
	chainloader (${root})/EFI/Microsoft/Boot/bootmgfw.efi
}
